### ISSUE TITLE
[META] test suite

### ISSUE THREAD

**Issue by hamilton** [hamilton/ply.js#1]
The test suite (and thus the library) should contain:

- [x] no data passed
- [x] a non-array passed
- [x] basic grouping
- [x] grouping numbers
- [x] grouping booleans
- [x] grouping `Date` objects
- [x] handling group values that are not strings or functions
- [x] reducing a plain dataset
- [x] reducing a grouped data set
- [x] handling reducer arguments that are an object of functions 
- [x] handling reducer arguments that are just a value
- [x] mapping a plain dataset
- [x] mapping a grouped data set
- [x] `.reset()` clears the `Ply` object

`Ply` Methods (used in reducer):
- [x] `Ply.sum`
- [x] `Ply.mean`
- [x] `Ply.standardDeviation`
- [x] `Ply.variance`
- [x] `Ply.max`
- [x] `Ply.min`
- [x] `Ply.quantile` number / array of values
- [x] `Ply.median`
- [x] `Ply.IQR`
- [x] `Ply.mode`

**Comment by hamilton** [comment]
This is probably enough functionality for 0.1. Going to close this.
