### ISSUE TITLE
[META] replace Ply with a Dataframe

### ISSUE THREAD

**Issue by hamilton** [hamilton/ply.js#12]
We want to expose a `Dataframe` class that allows for the kind of manipulation, subsetting, pivoting, and grouping we currently have with `Ply`. It will replace `Ply`, in fact. It should:

- [x] allow creation of empty frame
- [ ] surface extensive options for naming columns, naming rows, etc. in constructor and elsewhere
- [x] get / set rowNames / columnNames
- [x] simple `get` a row based on index
- [x] have an easy way to append/delete a row/column to/from the data set
- [ ] have all the same data manipulation functions as `Ply`
- [ ] add the `gather` and `spread` functions
- [ ] function for joining two `Dataframe` objects
- [ ] have an easy way to read in a csv of various sizes (both batched & streaming)

**Comment by hamilton** [comment]
I'm not actually sure this is really going to be that valuable in the medium term. Ply works great for casual data manipulation as-is.

**Comment by mhkeller** [comment]
Really neat library! I was looking for a good `gather` / `spread` node library but didn't find anything super great. If you have plans in the future to add that functionality to this or another library, that would be super useful, imo.

**Comment by hamilton** [comment]
Thanks @mhkeller! I definitely have plans to add those two to this library as the need arises. I have mostly only worked on this when I've needed to add more features for my own work, but would be happy to accept a PR on this. If this library turns out to be useful, it may end up getting moved over to the @iodide-project (which for me was the main motivation for having a tidy-data lib that works with csv-style arrays of objects) and published to NPM. There is a bit of clunkiness to my implementation that I want to fix down the line. 

What are you using this for?

**Comment by mhkeller** [comment]
Ya I think having a Node-equivalent of tidy is really interesting. I do most of my scraping or data cleaning in Node so my interest is in having those methods available in a nicely supported library. I find it's pretty common in dataviz to store your data in, say, a wide format but the chart logic makes more sense to have things in a long format (or a long format is then grouped).
